name: Wake up App
on:
  schedule:
    - cron: '0 */10 * * *' # LÃ¤uft alle 10 Stunden
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Keep alive commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo $(date) > last_ping.txt
          git add last_ping.txt
          git commit -m "Keep alive ping"
          git push
