name: Wake up App
on:
  schedule:
    - cron: '0 */6 * * *' # Läuft alle 6 Stunden
  workflow_dispatch:      # Ermöglicht manuelles Starten zum Testen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Keep alive commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Ein leerer Commit verhindert, dass die Action fehlschlägt, wenn sich nichts geändert hat
          git commit --allow-empty -m "Keep alive heartbeat"
          git push
